
version: "3"

services:
  web:
    restart: always
    depends_on:
      - redis
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 20s
      timeout: 10s
      retries: 3

  redis:
    restart: always

  db:
    restart: always

