
version: "2"

services:
  web:
    command: python3 /data/app/app_tornado.py -c deploy -p 8080
    restart: always
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 20s
      timeout: 10s
      retries: 3

