
version: "2"

services:
  web:
    build: ./app
    container_name: portal_web
    command: python3 /data/app/app.py -c dev
    volumes:
      - ./app:/data/app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
     - ./redis:/data
    restart: unless-stopped

  db:
    image: "mysql:5"
    container_name: "db_mysql"
    volumes:
      - ./db/data:/data
      - ./db/etc/mysql:/etc/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=stensal_web
      - MYSQL_ROOT_PASSWORD=dec2017t@

