
version: "3"

services:
  web:
    build: ./app
    command: python3 /data/app/app.py -c dev
    volumes:
      - ./app:/data/app
    ports:
      - "8080:8080"

  redis:
    image: "redis:latest"
    container_name: redis

  db:
    image: "mysql:5"
    container_name: "db_mysql"
    volumes:
      - ./db/data:/data
      - ./db/etc/mysql:/etc/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stensal_web
      - MYSQL_ROOT_PASSWORD=dec2017t@

