
version: "2"

services:
  tests_web:
    build: ./app
    container_name: portal_web_tests
    command: "/bin/bash -c 'python3 /data/app/init_db.py -c tests && sleep 3650d'"
    volumes:
      - ./app:/data/app
    restart: "unless-stopped"
    stdin_open: true
    tty: true
    depends_on:
      - tests_db

  tests_db:
    image: "mysql:5"
    container_name: "db_mysql_tests"
    command: mysqld
    volumes:
      - ./db/test-data:/data
      - ./db/mysql_cli.sh:/data/mysql_cli.sh
      - ./db/etc/mysql:/etc/mysql
    restart: "unless-stopped"
    environment:
      - MYSQL_DATABASE=stensal_web
      - MYSQL_ROOT_PASSWORD=dec2017t@


